// Common project data shared across all variations
window.PROJECTS = [
  {
    id: 'p01',
    num: '01',
    title: 'Pixel Forge',
    desc: 'ドット絵を即座にSVGへ変換するブラウザツール。レイヤー管理とパレット抽出機能つき。',
    repo: 'username/pixel-forge',
    tags: ['Tool', 'Canvas', 'TS'],
    status: 'LIVE',
    accent: 'cyan',
  },
  {
    id: 'p02',
    num: '02',
    title: 'Lattice',
    desc: 'Markdownで書ける格子状のメモ帳。リンクが自動でグラフ可視化される実験的なノートアプリ。',
    repo: 'username/lattice',
    tags: ['App', 'Graph', 'WASM'],
    status: 'BETA',
    accent: 'magenta',
  },
  {
    id: 'p03',
    num: '03',
    title: 'Resonance',
    desc: 'Web Audio APIだけで作ったシンセサイザー。MIDI入力とプリセット共有に対応。',
    repo: 'username/resonance',
    tags: ['Audio', 'MIDI', 'JS'],
    status: 'LIVE',
    accent: 'lime',
  },
  {
    id: 'p04',
    num: '04',
    title: 'Driftnet',
    desc: 'P2Pでファイルを直接受け渡すための実験。WebRTCとQRコードで接続を確立する。',
    repo: 'username/driftnet',
    tags: ['Network', 'WebRTC'],
    status: 'WIP',
    accent: 'cyan',
  },
  {
    id: 'p05',
    num: '05',
    title: 'Glyph Lab',
    desc: '可変フォントを遊ぶための実験室。軸のスライダーをアニメーションで保存できる。',
    repo: 'username/glyph-lab',
    tags: ['Type', 'Animation'],
    status: 'LIVE',
    accent: 'magenta',
  },
];
